### ISSUE TITLE
Goddamn Kramse, what a typo!

### ISSUE THREAD

**Issue by Dalle-valle** [kramse/security-courses#8]
in 7-defensive-architecture-security-in-web.tex 

Typo on line 243 _" \item Book references NIST 30-60 times less when remove vulnerability"_

Should be "\item Book references NIST 30-60 times less when removing a vulnerability"

**Comment by kramse** [comment]
Thank you!

I have updated source .tex, pdf and uploaded again to Fronter!
Closing
